name: CI

on:
  push:

jobs:
  get-lts-version:
    name: Get LTS for Golang
    runs-on: ubuntu-slim
    outputs:
      lts_versions_fetched: ${{ steps.getLTSversion.outputs.lts_versions }}

    steps:
      - name: Checkout code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Get LTS for Golang
        uses: paulie-of-punskas/get-lts-versions@6e9d3fcd7129bdbb9596737a1842224b866f3e43 # v1.0.2
        id: getLTSversion
        with:
          language: 'golang'
          versions_to_fetch: '3'

  setup-lts-environment:
    name: Setup environment | Go ${{ matrix.lts_version }}
    runs-on: ubuntu-22.04
    needs: get-lts-version
    strategy:
      matrix:
        lts_version: ${{ fromJson(needs.get-lts-version.outputs.lts_versions_fetched) }}
    steps:
      - name: Set up environment
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version: ${{ matrix.lts_version }}
          architecture: 'x64'

      - name: Run build
        shell: bash
        run: go build .
